// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("calendar.caldav.googleResync", 1706627500);
user_pref("calendar.list.sortOrder", "2cb98868-19a9-414a-be83-99683fb4fb9b");
user_pref("calendar.registry.2cb98868-19a9-414a-be83-99683fb4fb9b.calendar-main-default", true);
user_pref("calendar.registry.2cb98868-19a9-414a-be83-99683fb4fb9b.calendar-main-in-composite", true);
user_pref("calendar.registry.2cb98868-19a9-414a-be83-99683fb4fb9b.disabled", true);
user_pref("calendar.registry.2cb98868-19a9-414a-be83-99683fb4fb9b.name", "Home");
user_pref("calendar.registry.2cb98868-19a9-414a-be83-99683fb4fb9b.type", "storage");
user_pref("calendar.registry.2cb98868-19a9-414a-be83-99683fb4fb9b.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1706627497);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231215200246");
user_pref("extensions.lastAppVersion", "115.6.0");
user_pref("extensions.lastPlatformVersion", "115.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"8bc56cf5-46e7-4942-af18-4d309b6487c1\",\"google@search.mozilla.org\":\"fa071788-ab4c-405e-a27b-ec6d34206d92\",\"ddg@search.mozilla.org\":\"ae5fb2dc-82dc-4743-9275-6657e3629956\",\"amazondotcom@search.mozilla.org\":\"4d3c2801-31fc-4cae-84a0-0a9c32485dc2\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.6.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1706627478);
user_pref("toolkit.telemetry.cachedClientID", "4533a2de-a75a-4abb-896e-46e9ade1078b");
user_pref("toolkit.telemetry.previousBuildID", "20231215200246");
